spring:
  profiles:
    active: pure_jwt
  datasource:
    url: jdbc:mysql://localhost:3306/ktb_community?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
jwt:
  expiration:
    access: 86400000
    refresh: 1209600000
  secret: ${JWT_SECRET}


logging:
  level:
    org.hibernate.SQL: debug